runtime: nodejs16
service: log-viewer
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
    # Add cache control headers to always check for updates
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    # Add cache control headers to always check for updates
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"