# Yaml file responsable deployning Java app to GCP app Engine

runtime: java11

# The service deployed
service: java-be


instance_class: F2
env: standard

handlers:
  - url: /(.*\..+)$
    script: auto

health_check:
  enable_health_check: False

automatic_scaling:
  min_instances: 3
  max_instances: 5
  cool_down_period_sec: 180
#  cpu_utilization:
#    target_utilization: 0.5
