runtime: python39

service: logs-websocket

entrypoint: python main.py

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: /app/creds.json

beta_settings:
  cloud_sql_instances: <CLOUD_SQL_INSTANCE_CONNECTION_NAME>

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 1
  target_cpu_utilization: 0.5
