#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 921223709112-1jjqhh9bsg31u3hq6v05dcrgm9ta9i88.apps.googleusercontent.com
#            client-secret: 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
#            redirectUri: https://java-be-dot-pg-ae-n-app-662190.uc.r.appspot.com/login/oauth2/code/google
#            scope:
#              - email
#              - profile
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/pwcoffering
#    username: offeringmansql
#    password: ',Gt5<+T^12Zal~6$'
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://34.29.175.96:3306/pwcofferingMain
#    username: offeringmansql
#    password: ',Gt5<+T^12Zal~6$'
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  cloud:
#    gcp:
#      sql:
#        enabled: false
#        database-type: mysql
#        database-name: pwcofferingMain
#        instance-connection-name: pg-ae-n-app-662190:us-central1:pwcoffering


